### ISSUE TITLE
Fides v0.8.0 update

### ISSUE THREAD

**Issue by max-de-rooij** [sebapersson/Fides.jl#8]
When testing the package and running the rosenbrock example from the docs I get the error:

```
ERROR: LoadError: Python: TypeError: BFGS.__init__() got an unexpected keyword argument 'init_with_hess'
Python stacktrace: none
```

Fides v0.8.0 indeed removed this keyword argument so probably this is the reason for the error.

**Comment by sebapersson** [comment]
Thanks for reporting!

I agree that this is likely an issue with Fides v0.8.0 changing the Hessian handling. Until I get this fixed, using an earlier version of Fides should work (as I am myself using Fides.jl with an earlier Fides version without any problems currently)

**Comment by sebapersson** [comment]
Thanks again for reporting. In Fides.jl v1.2 everything should now work with fides v0.8.
